# Generated by Django 5.2.10 on 2026-01-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_safetywalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppe', models.BooleanField(default=False)),
                ('work', models.BooleanField(default=False)),
                ('environment', models.BooleanField(default=False)),
                ('reaction', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.employee')),
                ('safety_walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.safetywalk')),
            ],
        ),
    ]
