# Generated by Django 5.2.10 on 2026-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_area_reaction_alter_safetywalk_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetywalk',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
