# Generated by Django 5.2.10 on 2026-01-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='safety_walk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.safetywalk'),
        ),
    ]
