# Generated by Django 5.2.10 on 2026-01-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_observation_safety_walk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='safety_walk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='core.safetywalk'),
        ),
    ]
